// ═══════════════════════════════════════════
// ALGORITHM REGISTRY
// ═══════════════════════════════════════════
const ALGOS = {
  bubble:{name:"Bubble Sort",cat:"Sorting",badge:"O(n²)",desc:"Repeatedly swap adjacent elements if out of order. Stops early if no swaps.",type:"sort",
    code:["<span class='kw'>function</span> <span class='fn'>bubbleSort</span>(arr):","  n = arr.length","  <span class='kw'>for</span> i = 0 <span class='kw'>to</span> n-1:","    swapped = <span class='kw'>false</span>","    <span class='kw'>for</span> j = 0 <span class='kw'>to</span> n-i-2:","      <span class='kw'>if</span> arr[j] > arr[j+1]:","        swap(arr[j], arr[j+1])","        swapped = <span class='kw'>true</span>","    <span class='kw'>if</span> !swapped: <span class='kw'>break</span>","  <span class='kw'>return</span> arr"],
    info:"<b>Time:</b> O(n²) avg/worst &bull; O(n) best<br><b>Space:</b> O(1)<br><b>Stable:</b> Yes",
    cases:["Already sorted → O(n) due to early exit","All equal → max comparisons, zero swaps","Reverse sorted → worst case n(n-1)/2 swaps","Single element → returns immediately"]},
  merge:{name:"Merge Sort",cat:"Sorting",badge:"O(n log n)",desc:"Divide array recursively then merge sorted halves. Stable, consistent O(n log n).",type:"sort",
    code:["<span class='kw'>function</span> <span class='fn'>mergeSort</span>(arr):","  <span class='kw'>if</span> arr.length <= 1: <span class='kw'>return</span>","  mid = arr.length / 2","  left  = mergeSort(arr[0..mid])","  right = mergeSort(arr[mid..])","  <span class='kw'>return</span> <span class='fn'>merge</span>(left, right)","","<span class='kw'>function</span> <span class='fn'>merge</span>(L, R):","  result = []","  <span class='kw'>while</span> L and R not empty:","    <span class='kw'>if</span> L[0] <= R[0]: result.push(L.shift())","    <span class='kw'>else</span>: result.push(R.shift())","  <span class='kw'>return</span> [...result, ...L, ...R]"],
    info:"<b>Time:</b> O(n log n) all cases<br><b>Space:</b> O(n) auxiliary<br><b>Stable:</b> Yes",
    cases:["Single element → base case","Already sorted → still splits fully","Stack depth: O(log n) recursive calls"]},
  quick:{name:"Quick Sort",cat:"Sorting",badge:"O(n log n)",desc:"Pick pivot, partition around it, recursively sort sub-arrays.",type:"sort",
    code:["<span class='kw'>function</span> <span class='fn'>quickSort</span>(arr, lo, hi):","  <span class='kw'>if</span> lo >= hi: <span class='kw'>return</span>","  p = <span class='fn'>partition</span>(arr, lo, hi)","  quickSort(arr, lo, p-1)","  quickSort(arr, p+1, hi)","","<span class='kw'>function</span> <span class='fn'>partition</span>(arr, lo, hi):","  pivot = arr[hi]","  i = lo - 1","  <span class='kw'>for</span> j = lo <span class='kw'>to</span> hi-1:","    <span class='kw'>if</span> arr[j] <= pivot: i++; swap(arr[i],arr[j])","  swap(arr[i+1], arr[hi])","  <span class='kw'>return</span> i + 1"],
    info:"<b>Time:</b> O(n log n) avg &bull; O(n²) worst<br><b>Space:</b> O(log n)<br><b>Stable:</b> No",
    cases:["Sorted array with last-element pivot → O(n²)","All equal elements → O(n²) without 3-way partition"]},
  sort_compare:{name:"Compare Sorts",cat:"Sorting",badge:"Head-to-Head",desc:"Race all 4 sorting algorithms on the same array simultaneously. Compare comparisons, swaps, and total steps.",type:"sort_compare",
    code:["<span class='cm'>// ── Complexity Summary ──</span>","","<span class='cm'>Bubble Sort</span>","<span class='kw'>Time:</span>  O(n²) avg / worst","<span class='kw'>Space:</span> O(1) &bull; Stable: Yes","","<span class='cm'>Merge Sort</span>","<span class='kw'>Time:</span>  O(n log n) always","<span class='kw'>Space:</span> O(n) &bull; Stable: Yes","","<span class='cm'>Quick Sort</span>","<span class='kw'>Time:</span>  O(n log n) avg","<span class='kw'>Space:</span> O(log n) &bull; Stable: No","","<span class='cm'>Heap Sort</span>","<span class='kw'>Time:</span>  O(n log n) always","<span class='kw'>Space:</span> O(1) &bull; Stable: No"],
    info:"<b>Comparisons:</b> Element checks.<br><b>Swaps:</b> In-place moves.<br><b>Writes:</b> Array assignments (merge).<br><b>Steps:</b> Total animation frames.",
    cases:["Merge Sort: best worst-case but O(n) extra memory","Quick Sort: fastest in practice on random data","Heap Sort: O(1) space but poor cache locality","Bubble Sort: O(n) best-case on nearly-sorted arrays"]},
  heap:{name:"Heap Sort",cat:"Sorting",badge:"O(n log n)",desc:"Build a max-heap then repeatedly extract maximum. In-place, O(n log n) guaranteed.",type:"sort",
    code:["<span class='kw'>function</span> <span class='fn'>heapSort</span>(arr):","  n = arr.length","  <span class='kw'>for</span> i = n/2-1 <span class='kw'>downto</span> 0: heapify(arr,n,i)","  <span class='kw'>for</span> i = n-1 <span class='kw'>downto</span> 1:","    swap(arr[0], arr[i])","    heapify(arr, i, 0)","","<span class='kw'>function</span> <span class='fn'>heapify</span>(arr, n, i):","  largest = i","  l = 2*i+1, r = 2*i+2","  <span class='kw'>if</span> l<n and arr[l]>arr[largest]: largest=l","  <span class='kw'>if</span> r<n and arr[r]>arr[largest]: largest=r","  <span class='kw'>if</span> largest != i: swap; heapify(arr,n,largest)"],
    info:"<b>Time:</b> O(n log n) all cases<br><b>Space:</b> O(1)<br><b>Stable:</b> No",
    cases:["Build phase is O(n) — non-obvious","Not stable: equal elements may change order","Single element → heapify is a no-op"]},

  sliding:{name:"Sliding Window",cat:"Array",badge:"O(n)",desc:"Fixed-size window for max-sum. Brute recomputes each window from scratch; optimal slides in O(1) per step.",type:"array_sw",
    code:["<span class='kw'>function</span> <span class='fn'>slidingWindow</span>(arr, k):","  sum = Σ arr[0..k-1]","  max = sum; maxStart = 0","  <span class='kw'>for</span> i = 1 <span class='kw'>to</span> n-k:","    sum += arr[i+k-1]","    sum -= arr[i-1]","    <span class='kw'>if</span> sum > max: max=sum; maxStart=i","  <span class='kw'>return</span> max, maxStart"],
    info:"<b>Time:</b> O(n)<br><b>Space:</b> O(1)<br><b>Use case:</b> Subarray sums, max lengths",
    cases:["k > array length → invalid","k = 1 → max sum = max element","All negatives → max sum = least-negative window"]},

  twoptr:{name:"Two Pointer",cat:"Array",badge:"O(n)",desc:"Find a pair summing to target. Brute checks all O(n²) pairs; optimal uses sorted order to converge from both ends in O(n).",type:"array_tp",
    approaches:[
      {key:'brute',  label:'Brute',   badge:'O(n²)', color:'#ff4081'},
      {key:'optimal',label:'Optimal', badge:'O(n)',  color:'#00e676'},
    ],
    approachCodes:{
      brute:["<span class='kw'>function</span> <span class='fn'>bruteTwoSum</span>(arr, target):","  <span class='kw'>for</span> i = 0 <span class='kw'>to</span> n-2:","    <span class='kw'>for</span> j = i+1 <span class='kw'>to</span> n-1:  <span class='cm'>← inner loop</span>","      <span class='kw'>if</span> arr[i] + arr[j] == target:","        <span class='kw'>return</span> [i, j]","  <span class='kw'>return</span> -1","","<span class='cm'>// Checks every pair (i,j) — O(n²)</span>","<span class='cm'>// Ignores the sorted property entirely</span>"],
      optimal:["<span class='kw'>function</span> <span class='fn'>twoSum</span>(arr, target):","  left = 0; right = n - 1","  <span class='kw'>while</span> left < right:","    sum = arr[left] + arr[right]","    <span class='kw'>if</span> sum == target: <span class='kw'>return</span> [left, right]","    <span class='kw'>else if</span> sum < target: left++","    <span class='kw'>else</span>: right--","  <span class='kw'>return</span> -1","","<span class='cm'>// Sorted order: move L up if sum too small</span>","<span class='cm'>// Move R down if sum too large — O(n)</span>"],
    },
    approachInfo:{
      brute:"<b>Time:</b> O(n²) — nested loop checks every pair (i, j)<br><b>Space:</b> O(1)<br><b>Problem:</b> Ignores sorted order — every comparison is wasted work",
      optimal:"<b>Time:</b> O(n) — sorted array lets each pointer move at most n steps<br><b>Space:</b> O(1)<br><b>Key insight:</b> sum too small → move L right; sum too large → move R left",
    },
    code:["<span class='kw'>function</span> <span class='fn'>twoSum</span>(arr, target):","  left = 0; right = arr.length - 1","  <span class='kw'>while</span> left < right:","    sum = arr[left] + arr[right]","    <span class='kw'>if</span> sum == target: <span class='kw'>return</span> [left, right]","    <span class='kw'>else if</span> sum < target: left++","    <span class='kw'>else</span>: right--","  <span class='kw'>return</span> -1"],
    info:"<b>Time:</b> O(n)<br><b>Space:</b> O(1)<br><b>Requires:</b> Sorted array",
    cases:["Array not sorted → wrong results","No pair sums to target → pointers meet, return -1","Target < 2×min → impossible immediately"]},

  kadane:{name:"Kadane's Algorithm",cat:"Array",badge:"O(n)",desc:"Max subarray sum. Brute tries every subarray in O(n²); Kadane exploits the insight that a negative prefix is never worth extending.",type:"array_kadane",
    approaches:[
      {key:'brute',  label:'Brute',   badge:'O(n²)', color:'#ff4081'},
      {key:'optimal',label:'Optimal', badge:'O(n)',  color:'#00e676'},
    ],
    approachCodes:{
      brute:["<span class='kw'>function</span> <span class='fn'>bruteMaxSub</span>(arr):","  maxSum = -∞","  <span class='kw'>for</span> i = 0 <span class='kw'>to</span> n-1:  <span class='cm'>← start</span>","    sum = 0","    <span class='kw'>for</span> j = i <span class='kw'>to</span> n-1:  <span class='cm'>← end</span>","      sum += arr[j]","      <span class='kw'>if</span> sum > maxSum:","        maxSum = sum","        best = [i, j]","  <span class='kw'>return</span> maxSum"],
      optimal:["<span class='kw'>function</span> <span class='fn'>kadane</span>(arr):","  curSum = maxSum = arr[0]","  <span class='kw'>for</span> i = 1 <span class='kw'>to</span> n-1:","    <span class='kw'>if</span> curSum + arr[i] < arr[i]:","      curSum = arr[i]  <span class='cm'>// reset — negative prefix</span>","    <span class='kw'>else</span>:","      curSum += arr[i]","    maxSum = max(maxSum, curSum)","  <span class='kw'>return</span> maxSum"],
    },
    approachInfo:{
      brute:"<b>Time:</b> O(n²) — considers all n(n+1)/2 subarrays<br><b>Space:</b> O(1)<br><b>Problem:</b> Restarts from scratch each time — overlapping sums recomputed",
      optimal:"<b>Time:</b> O(n)<br><b>Space:</b> O(1)<br><b>Key insight:</b> If curSum + next &lt; next, a negative prefix is dragging us down — reset and start fresh at next",
    },
    code:["<span class='kw'>function</span> <span class='fn'>kadane</span>(arr):","  maxSum = curSum = arr[0]","  start = end = 0","  <span class='kw'>for</span> i = 1 <span class='kw'>to</span> n-1:","    <span class='kw'>if</span> curSum + arr[i] < arr[i]:","      curSum = arr[i]  <span class='cm'>// reset window</span>","    <span class='kw'>else</span>: curSum += arr[i]","    <span class='kw'>if</span> curSum > maxSum: maxSum = curSum","  <span class='kw'>return</span> maxSum"],
    info:"<b>Time:</b> O(n)<br><b>Space:</b> O(1)<br><b>Use:</b> Stock profit, signal peaks",
    cases:["All negatives → maxSum = least-negative element","All zeros → maxSum = 0","Single element → trivially returned"]},

  boyermoore:{name:"Boyer-Moore Vote",cat:"Array",badge:"O(n)",desc:"Majority element. Brute counts every element's frequency in O(n²); Boyer-Moore finds the same answer in O(n) time using O(1) space.",type:"array_bm",
    approaches:[
      {key:'brute',  label:'Brute',      badge:'O(n²)',    color:'#ff4081'},
      {key:'optimal',label:'Boyer-Moore', badge:'O(1) space',color:'#00e676'},
    ],
    approachCodes:{
      brute:["<span class='kw'>function</span> <span class='fn'>bruteMajority</span>(arr):","  <span class='kw'>for</span> i = 0 <span class='kw'>to</span> n-1:","    count = 0","    <span class='kw'>for</span> j = 0 <span class='kw'>to</span> n-1:  <span class='cm'>← inner scan</span>","      <span class='kw'>if</span> arr[j] == arr[i]: count++","    <span class='kw'>if</span> count > n/2:","      <span class='kw'>return</span> arr[i]","  <span class='kw'>return</span> null","","<span class='cm'>// Counts frequency of each element — O(n²)</span>"],
      optimal:["<span class='kw'>function</span> <span class='fn'>majorityVote</span>(arr):","  candidate = null; count = 0","  <span class='kw'>for</span> x <span class='kw'>in</span> arr:  <span class='cm'>// Phase 1</span>","    <span class='kw'>if</span> count == 0: candidate = x; count = 1","    <span class='kw'>else if</span> x == candidate: count++","    <span class='kw'>else</span>: count--","  <span class='cm'>// Phase 2: verify candidate</span>","  votes = count(arr, candidate)","  <span class='kw'>return</span> candidate <span class='kw'>if</span> votes > n/2"],
    },
    approachInfo:{
      brute:"<b>Time:</b> O(n²) — counts each element's frequency via inner scan<br><b>Space:</b> O(1)<br><b>Problem:</b> Re-scans the entire array for every element; ignores majority property",
      optimal:"<b>Time:</b> O(n) &bull; <b>Space:</b> O(1)<br><b>Key insight:</b> A majority element survives all cancellations — it always remains as the last standing candidate",
    },
    code:["<span class='kw'>function</span> <span class='fn'>majorityVote</span>(arr):","  candidate=<span class='kw'>null</span>; count=0","  <span class='kw'>for</span> x <span class='kw'>in</span> arr:","    <span class='kw'>if</span> count == 0: candidate=x; count=1","    <span class='kw'>else if</span> x == candidate: count++","    <span class='kw'>else</span>: count--","  votes = count(arr, candidate)","  <span class='kw'>return</span> candidate <span class='kw'>if</span> votes > n/2","  <span class='kw'>else</span>: <span class='kw'>return</span> <span class='kw'>null</span>"],
    info:"<b>Time:</b> O(n)<br><b>Space:</b> O(1)<br><b>Requires:</b> Phase 2 verification",
    cases:["No majority → Phase 2 catches false positive","Same array → candidate set on first element","50/50 split → no majority, Phase 2 rejects"]},

  bfs_path:{name:"BFS Pathfinding",cat:"Pathfinding",badge:"Shortest Path",desc:"Explores level by level — guarantees shortest path on unweighted grids.",type:"grid",algo:"bfs",
    code:["<span class='kw'>function</span> <span class='fn'>BFS</span>(grid, start, end):","  queue = [start]; visited = {start: null}","  <span class='kw'>while</span> queue not empty:","    node = queue.shift()","    <span class='kw'>if</span> node == end: <span class='kw'>break</span>","    <span class='kw'>for</span> nb <span class='kw'>in</span> getNeighbors(node):","      <span class='kw'>if</span> nb not in visited:","        visited[nb] = node; queue.push(nb)","  <span class='kw'>return</span> reconstructPath(visited, end)"],
    info:"<b>Time:</b> O(V+E)<br><b>Space:</b> O(V)<br><b>Optimal:</b> Yes (unweighted)",
    cases:["Start = End → path length 0","End blocked → no path found","Multiple shortest paths → BFS finds one deterministically"]},
  dfs_path:{name:"DFS Pathfinding",cat:"Pathfinding",badge:"Explores Deep",desc:"Goes as deep as possible before backtracking. Does NOT guarantee shortest path.",type:"grid",algo:"dfs",
    code:["<span class='kw'>function</span> <span class='fn'>DFS</span>(grid, start, end):","  stack = [start]; visited = {start: null}","  <span class='kw'>while</span> stack not empty:","    node = stack.pop()","    <span class='kw'>if</span> node == end: <span class='kw'>break</span>","    <span class='kw'>for</span> nb <span class='kw'>in</span> getNeighbors(node):","      <span class='kw'>if</span> nb not in visited:","        visited[nb] = node; stack.push(nb)","  <span class='kw'>return</span> reconstructPath(visited, end)"],
    info:"<b>Time:</b> O(V+E)<br><b>Space:</b> O(V)<br><b>Optimal:</b> No",
    cases:["May find very long path when short one exists","End unreachable → stack empties, no path"]},
  dijkstra:{name:"Dijkstra's",cat:"Pathfinding",badge:"Weighted",desc:"Greedy shortest path on weighted graphs via priority queue.",type:"grid",algo:"dijkstra",
    code:["<span class='kw'>function</span> <span class='fn'>dijkstra</span>(grid, start, end):","  dist = {start:0, rest:∞}","  pq = MinHeap([(0, start)])","  <span class='kw'>while</span> pq not empty:","    (d, node) = pq.pop()","    <span class='kw'>if</span> node==end: <span class='kw'>break</span>","    <span class='kw'>for</span> (nb,w) in neighbors(node):","      nd = d + w","      <span class='kw'>if</span> nd < dist[nb]: dist[nb]=nd; pq.push((nd,nb))"],
    info:"<b>Time:</b> O((V+E) log V)<br><b>Space:</b> O(V)<br><b>Optimal:</b> Yes (non-neg weights)",
    cases:["Negative weights → wrong results","All weights equal → degenerates to BFS"]},
  astar:{name:"A* Search",cat:"Pathfinding",badge:"Heuristic",desc:"Dijkstra + Manhattan heuristic. Fastest when good heuristic is available.",type:"grid",algo:"astar",
    code:["<span class='kw'>function</span> <span class='fn'>aStar</span>(grid, start, end):","  open = MinHeap([(h, start)]); g={start:0}","  <span class='kw'>while</span> open not empty:","    (f, node) = open.pop()","    <span class='kw'>if</span> node==end: <span class='kw'>break</span>","    <span class='kw'>for</span> nb in neighbors(node):","      ng = g[node]+cost(node,nb)","      <span class='kw'>if</span> ng < g[nb]: g[nb]=ng; open.push((ng+h(nb),nb))"],
    info:"<b>Time:</b> O((V+E) log V)<br><b>Space:</b> O(V)<br><b>Optimal:</b> Yes (admissible h)",
    cases:["Inadmissible heuristic → may miss optimal path","h=0 everywhere → degenerates to Dijkstra"]},
  bfs_graph:{name:"BFS",cat:"Graph",subcat:"Graph Traversal",badge:"O(V+E)",desc:"Level-by-level traversal using a queue.",type:"graph",algo:"bfs",
    code:["<span class='kw'>function</span> <span class='fn'>BFS</span>(graph, start):","  queue=[start]; visited={start}","  <span class='kw'>while</span> queue not empty:","    node=queue.shift(); visit(node)","    <span class='kw'>for</span> nb <span class='kw'>in</span> adj[node]:","      <span class='kw'>if</span> nb not in visited:","        visited.add(nb); queue.push(nb)"],
    info:"<b>Time:</b> O(V+E)<br><b>Space:</b> O(V)",
    cases:["Disconnected graph → only reachable visited","Cycle → visited set prevents infinite loop"]},
  dfs_graph:{name:"DFS",cat:"Graph",subcat:"Graph Traversal",badge:"O(V+E)",desc:"Explore as deep as possible before backtracking.",type:"graph",algo:"dfs",
    code:["<span class='kw'>function</span> <span class='fn'>DFS</span>(node, visited):","  visited.add(node); visit(node)","  <span class='kw'>for</span> nb <span class='kw'>in</span> adj[node]:","    <span class='kw'>if</span> nb not in visited: DFS(nb, visited)"],
    info:"<b>Time:</b> O(V+E)<br><b>Space:</b> O(V) stack",
    cases:["Disconnected → outer loop needed","Very deep graph → may stack-overflow"]},
  topo:{name:"Topological Sort",cat:"Graph",subcat:"Graph Traversal",badge:"O(V+E)",desc:"Linear ordering of DAG vertices where each edge u→v has u before v.",type:"graph",algo:"topo",
    code:["<span class='kw'>function</span> <span class='fn'>topoSort</span>(graph):","  inDeg[v]=in-degree of each vertex","  queue=[v for v if inDeg[v]==0]","  result=[]","  <span class='kw'>while</span> queue not empty:","    node=queue.shift(); result.push(node)","    <span class='kw'>for</span> nb in adj[node]:","      <span class='kw'>if</span> --inDeg[nb]==0: queue.push(nb)","  <span class='kw'>return</span> result"],
    info:"<b>Time:</b> O(V+E)<br><b>Space:</b> O(V)<br><b>Requires:</b> DAG",
    cases:["Graph has cycle → result shorter than V","Multiple valid orderings → all correct"]},
  dsu:{name:"DSU / Union-Find",cat:"Graph",subcat:"Graph Traversal",badge:"O(α(n))",desc:"Disjoint Set Union with path compression and union by rank.",type:"dsu",
    code:["<span class='kw'>function</span> <span class='fn'>find</span>(x):","  <span class='kw'>if</span> parent[x]!=x: parent[x]=find(parent[x])","  <span class='kw'>return</span> parent[x]","","<span class='kw'>function</span> <span class='fn'>union</span>(x,y):","  rx=find(x); ry=find(y)","  <span class='kw'>if</span> rank[rx]<rank[ry]: swap(rx,ry)","  parent[ry]=rx","  <span class='kw'>if</span> rank[rx]==rank[ry]: rank[rx]++"],
    info:"<b>Time:</b> O(α(n)) per op<br><b>Space:</b> O(n)",
    cases:["Self-union → guard with find check","α(n) ≤ 4 in practice — essentially O(1)"]},
  tree:{name:"BST Operations",cat:"Tree",badge:"O(log n)",desc:"Binary Search Tree: insert, search, delete.",type:"tree",
    code:["<span class='kw'>function</span> <span class='fn'>insert</span>(root, val):","  <span class='kw'>if</span> !root: <span class='kw'>return</span> new Node(val)","  <span class='kw'>if</span> val<root.val: root.left=insert(root.left,val)","  <span class='kw'>else if</span> val>root.val: root.right=insert(root.right,val)","  <span class='kw'>return</span> root","","<span class='kw'>function</span> <span class='fn'>search</span>(root, val):","  <span class='kw'>if</span> !root or root.val==val: <span class='kw'>return</span> root","  <span class='kw'>if</span> val<root.val: <span class='kw'>return</span> search(root.left,val)","  <span class='kw'>return</span> search(root.right,val)"],
    info:"<b>Time:</b> O(log n) balanced &bull; O(n) skewed<br><b>Space:</b> O(h)",
    cases:["Sorted input → degenerates to linked list","Delete 2-child node → replace with inorder successor"]},
  tree_trav:{name:"Tree Traversals",cat:"Tree",badge:"O(n)",desc:"Inorder (L-Root-R), Preorder (Root-L-R), Postorder (L-R-Root) DFS traversals.",type:"tree_trav",
    code:["<span class='kw'>function</span> <span class='fn'>inorder</span>(node):","  inorder(node.left); visit(node); inorder(node.right)","","<span class='kw'>function</span> <span class='fn'>preorder</span>(node):","  visit(node); preorder(node.left); preorder(node.right)","","<span class='kw'>function</span> <span class='fn'>postorder</span>(node):","  postorder(node.left); postorder(node.right); visit(node)"],
    info:"<b>Inorder:</b> Sorted sequence in BST<br><b>Preorder:</b> Copy tree / prefix expr<br><b>Postorder:</b> Delete tree / postfix expr",
    cases:["Inorder on BST yields sorted sequence","Skewed tree → O(n) stack depth"]},

  dp_fib:{name:"Fibonacci",cat:"Dynamic Programming",badge:"O(n)",desc:"Compute Fₙ. Brute recursion is O(2ⁿ) due to redundant calls. Memoization caches top-down. Tabulation builds bottom-up.",type:"dp_fib",
    approaches:[
      {key:'brute',   label:'Brute Recursive', badge:'O(2ⁿ)', color:'#ff4081'},
      {key:'memo',    label:'Memoization',      badge:'O(n)',  color:'#ffc107'},
      {key:'optimal', label:'Tabulation',       badge:'O(n)',  color:'#00e676'},
    ],
    approachCodes:{
      brute:["<span class='kw'>function</span> <span class='fn'>fib</span>(n):","  <span class='cm'>// No cache — recomputes everything!</span>","  <span class='kw'>if</span> n <= 1: <span class='kw'>return</span> n","  <span class='kw'>return</span> <span class='fn'>fib</span>(n-1) + <span class='fn'>fib</span>(n-2)","","<span class='cm'>// fib(5)  → 15 total calls</span>","<span class='cm'>// fib(10) → 177 total calls</span>","<span class='cm'>// fib(20) → 21,891 total calls</span>","<span class='cm'>// fib(2) gets recomputed 3× for fib(5)!</span>"],
      memo:["<span class='kw'>function</span> <span class='fn'>fib</span>(n, memo={}):","  <span class='kw'>if</span> n<=1: <span class='kw'>return</span> n","  <span class='kw'>if</span> n <span class='kw'>in</span> memo:","    <span class='kw'>return</span> memo[n]  <span class='cm'>← cache hit!</span>","  memo[n] = fib(n-1,memo)+fib(n-2,memo)","  <span class='kw'>return</span> memo[n]","","<span class='cm'>// Each fib(k) computed exactly once</span>","<span class='cm'>// Top-down: recursion + cache</span>"],
      optimal:["<span class='kw'>function</span> <span class='fn'>fib</span>(n):","  dp[0]=0; dp[1]=1","  <span class='kw'>for</span> i = 2 <span class='kw'>to</span> n:","    dp[i] = dp[i-1] + dp[i-2]","  <span class='kw'>return</span> dp[n]","","<span class='cm'>// Bottom-up — no recursion overhead</span>","<span class='cm'>// Can reduce to O(1) space with 2 vars</span>"],
    },
    approachInfo:{
      brute:"<b>Time:</b> O(2ⁿ) — exponential recomputation<br><b>Space:</b> O(n) call stack<br><b>Problem:</b> fib(k) is recomputed exponentially many times — fib(2) alone is called O(fib(n)) times",
      memo:"<b>Time:</b> O(n) — each subproblem solved exactly once<br><b>Space:</b> O(n) memo table + O(n) call stack<br><b>Top-Down:</b> Recursion + cache; solves only the subproblems actually needed",
      optimal:"<b>Time:</b> O(n)<br><b>Space:</b> O(n) table — reducible to O(1) with two variables<br><b>Bottom-Up:</b> Iterative; no recursion overhead, no risk of stack overflow",
    },
    code:["<span class='kw'>function</span> <span class='fn'>fib</span>(n):","  dp[0]=0; dp[1]=1","  <span class='kw'>for</span> i = 2 <span class='kw'>to</span> n:","    dp[i] = dp[i-1] + dp[i-2]","  <span class='kw'>return</span> dp[n]"],
    info:"<b>Time:</b> O(n)<br><b>Space:</b> O(n)",
    cases:["Brute fib(30) makes ~1.3 million calls","Memo/tabulation both O(n) — tabulation avoids stack overflow","Can reduce tabulation to O(1) space: only keep previous two values"]},

  dp_ks:{name:"0/1 Knapsack",cat:"Dynamic Programming",badge:"O(nW)",desc:"Maximise value within weight capacity. Brute enumerates all 2ⁿ subsets recursively. DP fills an n×W table in O(nW).",type:"dp_ks",
    approaches:[
      {key:'brute',  label:'Brute Recursive', badge:'O(2ⁿ)',  color:'#ff4081'},
      {key:'optimal',label:'Tabulation',       badge:'O(nW)', color:'#00e676'},
    ],
    approachCodes:{
      brute:["<span class='kw'>function</span> <span class='fn'>ks</span>(i, remW):","  <span class='cm'>// Enumerate all 2^n subsets</span>","  <span class='kw'>if</span> i==0 or remW==0: <span class='kw'>return</span> 0","  <span class='kw'>if</span> wt[i] > remW:","    <span class='kw'>return</span> ks(i-1, remW)","  <span class='kw'>return</span> max(","    val[i] + ks(i-1, remW-wt[i]),","    ks(i-1, remW))","","<span class='cm'>// Same (i, remW) recomputed many times!</span>"],
      optimal:["<span class='kw'>function</span> <span class='fn'>knapsack</span>(wts, vals, W):","  dp[0..n][0..W] = 0","  <span class='kw'>for</span> i = 1 <span class='kw'>to</span> n:","    <span class='kw'>for</span> w = 0 <span class='kw'>to</span> W:","      <span class='kw'>if</span> wts[i-1] <= w:","        dp[i][w] = max(","          vals[i-1]+dp[i-1][w-wts[i-1]],","          dp[i-1][w])","      <span class='kw'>else</span>: dp[i][w] = dp[i-1][w]"],
    },
    approachInfo:{
      brute:"<b>Time:</b> O(2ⁿ) — tries all include/exclude combinations recursively<br><b>Space:</b> O(n) call stack<br><b>Problem:</b> The same (item_index, remaining_capacity) subproblem is recomputed repeatedly",
      optimal:"<b>Time:</b> O(n·W) — fills n×W table systematically<br><b>Space:</b> O(n·W) reducible to O(W)<br><b>Key insight:</b> Cache every (i, w) pair — each is computed exactly once",
    },
    code:["<span class='kw'>function</span> <span class='fn'>knapsack</span>(wts, vals, n, W):","  dp = (n+1) × (W+1) zeros","  <span class='kw'>for</span> i = 1 <span class='kw'>to</span> n:","    <span class='kw'>for</span> w = 0 <span class='kw'>to</span> W:","      <span class='kw'>if</span> wts[i-1] <= w:","        dp[i][w] = max(vals[i-1]+dp[i-1][w-wts[i-1]], dp[i-1][w])","      <span class='kw'>else</span>: dp[i][w] = dp[i-1][w]","  <span class='kw'>return</span> dp[n][W]"],
    info:"<b>Time:</b> O(nW)<br><b>Space:</b> O(nW)",
    cases:["All items exceed W → result is 0","Greedy (value/weight ratio) doesn't always work here","W=0 → always returns 0"]},

  dp_lcs:{name:"LCS",cat:"Dynamic Programming",badge:"O(mn)",desc:"Longest Common Subsequence. Brute recursive is O(2^m). DP fills an m×n table in O(mn).",type:"dp_lcs",
    approaches:[
      {key:'brute',  label:'Brute Recursive', badge:'O(2^m)', color:'#ff4081'},
      {key:'optimal',label:'Tabulation',       badge:'O(mn)',  color:'#00e676'},
    ],
    approachCodes:{
      brute:["<span class='kw'>function</span> <span class='fn'>lcs</span>(s1, s2, i, j):","  <span class='cm'>// No cache — exponential recomputation</span>","  <span class='kw'>if</span> i==0 or j==0: <span class='kw'>return</span> 0","  <span class='kw'>if</span> s1[i-1] == s2[j-1]:","    <span class='kw'>return</span> 1 + lcs(s1,s2,i-1,j-1)","  <span class='kw'>return</span> max(","    lcs(s1,s2,i-1,j),","    lcs(s1,s2,i,j-1))","","<span class='cm'>// lcs(i-1,j-1) recomputed in both branches!</span>"],
      optimal:["<span class='kw'>function</span> <span class='fn'>lcs</span>(s1, s2):","  dp[0..m][0..n] = 0","  <span class='kw'>for</span> i = 1 <span class='kw'>to</span> m:","    <span class='kw'>for</span> j = 1 <span class='kw'>to</span> n:","      <span class='kw'>if</span> s1[i-1] == s2[j-1]:","        dp[i][j] = dp[i-1][j-1] + 1","      <span class='kw'>else</span>:","        dp[i][j] = max(dp[i-1][j], dp[i][j-1])","  <span class='kw'>return</span> dp[m][n]"],
    },
    approachInfo:{
      brute:"<b>Time:</b> O(2^m) — two recursive branches at each mismatch<br><b>Space:</b> O(m+n) call stack<br><b>Problem:</b> lcs(i-1, j-1) recomputed in both match and skip branches",
      optimal:"<b>Time:</b> O(m·n) — each (i, j) cell computed exactly once<br><b>Space:</b> O(m·n) reducible to O(min(m,n))<br><b>Key insight:</b> Build answers bottom-up; no redundant work",
    },
    code:["<span class='kw'>function</span> <span class='fn'>lcs</span>(s1, s2):","  dp = (m+1) × (n+1) zeros","  <span class='kw'>for</span> i = 1 <span class='kw'>to</span> m:","    <span class='kw'>for</span> j = 1 <span class='kw'>to</span> n:","      <span class='kw'>if</span> s1[i-1]==s2[j-1]: dp[i][j]=dp[i-1][j-1]+1","      <span class='kw'>else</span>: dp[i][j]=max(dp[i-1][j],dp[i][j-1])","  <span class='kw'>return</span> dp[m][n]"],
    info:"<b>Time:</b> O(mn)<br><b>Space:</b> O(mn)",
    cases:["Identical strings → LCS = full string","No common chars → LCS = 0","LCS ≠ longest common substring (must be contiguous)"]},

  binexp:{name:"Binary Exponentiation",cat:"Number Theory",badge:"O(log b)",desc:"Compute aᵇ mod m. Naive multiplies b times in O(b). Fast exponentiation halves the problem each step — O(log b).",type:"binexp",
    approaches:[
      {key:'brute',  label:'Naive',     badge:'O(b)',     color:'#ff4081'},
      {key:'optimal',label:'Fast Expo', badge:'O(log b)', color:'#00e676'},
    ],
    approachCodes:{
      brute:["<span class='kw'>function</span> <span class='fn'>naivePow</span>(a, b, mod):","  result = 1","  <span class='kw'>for</span> i = 0 <span class='kw'>to</span> b-1:","    result = result × a % mod","  <span class='kw'>return</span> result","","<span class='cm'>// b = 10   → 10 multiplications</span>","<span class='cm'>// b = 1000 → 1000 multiplications</span>","<span class='cm'>// b = 10^9 → 10^9 steps — infeasible!</span>"],
      optimal:["<span class='kw'>function</span> <span class='fn'>fastPow</span>(a, b, mod):","  result = 1; a = a % mod","  <span class='kw'>while</span> b > 0:","    <span class='kw'>if</span> b & 1:","      result = result × a % mod","    a = a × a % mod  <span class='cm'>← square</span>","    b >>= 1          <span class='cm'>← halve</span>","  <span class='kw'>return</span> result","","<span class='cm'>// b = 1000 → only ~10 multiplications</span>"],
    },
    approachInfo:{
      brute:"<b>Time:</b> O(b) — one multiplication per exponent step<br><b>Space:</b> O(1)<br><b>Problem:</b> Completely infeasible for large b (e.g. b = 10⁹ in competitive programming)",
      optimal:"<b>Time:</b> O(log b) — halves exponent each iteration<br><b>Space:</b> O(1)<br><b>Key insight:</b> a^b = (a²)^(b/2) if b even; a·(a²)^((b-1)/2) if odd",
    },
    code:["<span class='kw'>function</span> <span class='fn'>fastPow</span>(a, b, mod):","  result = 1; a = a % mod","  <span class='kw'>while</span> b > 0:","    <span class='kw'>if</span> b & 1:","      result = result × a % mod","    a = a × a % mod","    b >>= 1","  <span class='kw'>return</span> result"],
    info:"<b>Time:</b> O(log b)<br><b>Space:</b> O(1)<br><b>Use:</b> Modular arithmetic, RSA, Fermat primality",
    cases:["b=0 → result always 1","a=0 → result always 0","Large b (10⁹) → brute infeasible; O(log b) essential"]},

  xor:{name:"XOR Trick",cat:"Number Theory",badge:"O(n)",desc:"Find the single non-duplicated element. All duplicates cancel (a⊕a=0), unique survives.",type:"xor",
    code:["<span class='kw'>function</span> <span class='fn'>findUnique</span>(arr):","  result = 0","  <span class='kw'>for</span> x <span class='kw'>in</span> arr:","    result ^= x  <span class='cm'>// a⊕a=0, a⊕0=a</span>","  <span class='kw'>return</span> result"],
    info:"<b>Time:</b> O(n)<br><b>Space:</b> O(1)<br><b>Key:</b> XOR is self-inverse",
    cases:["Multiple unique elements → won't isolate","Works with negative numbers (two's complement)"]},
  bin_dec:{name:"Binary ↔ Decimal",cat:"Number Theory",badge:"O(n)",desc:"Convert binary↔decimal via positional values and repeated division.",type:"bin_dec",
    code:["<span class='kw'>function</span> <span class='fn'>binToDec</span>(bits):","  result = 0","  <span class='kw'>for</span> i = 0 <span class='kw'>to</span> n-1:","    <span class='kw'>if</span> bits[i]==1: result += 2^(n-1-i)","  <span class='kw'>return</span> result","","<span class='kw'>function</span> <span class='fn'>decToBin</span>(n):","  <span class='kw'>while</span> n > 0:","    bits.prepend(n%2); n=floor(n/2)"],
    info:"<b>Bin→Dec:</b> positional sum<br><b>Dec→Bin:</b> repeated ÷2, remainders reversed",
    cases:["Input 0 → binary is '0'","Leading zeros safely stripped"]},
  nim:{name:"Nim Game",cat:"Game Theory",badge:"XOR Strategy",desc:"Remove objects from heaps. Last to take wins. Optimal play via XOR.",type:"nim",
    code:["<span class='kw'>function</span> <span class='fn'>nimWin</span>(heaps):","  xorSum = XOR of all heaps","  <span class='kw'>return</span> xorSum != 0","","<span class='kw'>function</span> <span class='fn'>nimMove</span>(heaps):","  xorSum = XOR of all heaps","  <span class='kw'>for</span> i,h in heaps:","    target=h^xorSum","    <span class='kw'>if</span> target<h: heap[i]=target"],
    info:"<b>Losing pos:</b> XOR=0<br><b>Winning pos:</b> XOR≠0",
    cases:["XOR=0 → first player loses with optimal","Misère Nim → strategy flips at end-game"]},
  grundy:{name:"Grundy Numbers",cat:"Game Theory",badge:"Sprague-Grundy",desc:"Compute nimber values. Determines winner of any impartial game.",type:"grundy",
    code:["<span class='kw'>function</span> <span class='fn'>grundy</span>(n):","  G[0]=0","  <span class='kw'>for</span> i=1 to n:","    reach=Set()","    <span class='kw'>for</span> m in getMoves(i): reach.add(G[i-m])","    G[i]=mex(reach)","  <span class='kw'>return</span> G"],
    info:"<b>G[i]=0</b> → Losing<br><b>G[i]>0</b> → Winning",
    cases:["G[0]=0 always (terminal = losing)","Moves={1,2} → G cycles 0,1,2,0,1,2..."]},
  cycle_u:{name:"Cycle Detection (Undirected)",cat:"Graph",subcat:"Cycles",badge:"DFS Coloring",desc:"Back edge to gray non-parent node = cycle.",type:"cycle_u",
    code:["<span class='kw'>function</span> <span class='fn'>dfs</span>(u, parent):","  color[u]=GRAY","  <span class='kw'>for</span> v in adj[u]:","    <span class='kw'>if</span> WHITE: dfs(v,u)","    <span class='kw'>elif</span> GRAY and v≠parent:","      <span class='kw'>return</span> CYCLE FOUND","  color[u]=BLACK"],
    info:"<b>Time:</b> O(V+E)<br><b>Space:</b> O(V)",
    cases:["Tree → all BLACK, no cycle","Self-loop → node is own GRAY neighbor"]},
  cycle_d:{name:"Cycle Detection (Directed)",cat:"Graph",subcat:"Cycles",badge:"DFS Coloring",desc:"Back edge to GRAY node on recursion stack = cycle.",type:"cycle_d",
    code:["<span class='kw'>function</span> <span class='fn'>dfs</span>(u):","  color[u]=GRAY  <span class='cm'>← on stack</span>","  <span class='kw'>for</span> v in adj[u]:","    <span class='kw'>if</span> GRAY: <span class='kw'>return</span> CYCLE","    <span class='kw'>elif</span> WHITE: dfs(v)","  color[u]=BLACK"],
    info:"<b>Time:</b> O(V+E)<br><b>Space:</b> O(V)",
    cases:["BLACK neighbor → safe (cross/forward edge)","DAG → all nodes finish BLACK"]},
};

const CATS=[
  {key:"Sorting",icon:"⇅"},{key:"Array",icon:"▣"},{key:"Pathfinding",icon:"◎"},
  {key:"Graph",icon:"⬡",subcats:["Graph Traversal","Cycles"]},{key:"Tree",icon:"⌥"},
  {key:"Dynamic Programming",icon:"◈"},{key:"Number Theory",icon:"#"},{key:"Game Theory",icon:"♟"},
];
